import type { EntityDefinition } from '@/engine/types'

export const roomEntities: EntityDefinition[] = [
  {
    id: 'floor',
    label: 'Gallery Floor',
    category: 'architecture',
    semanticRole: 'ground plane',
    selectable: true,
    materialCategory: 'stone',
    defaultMaterialId: 'stone-travertine',
    description: 'A honed stone plate that registers every change in sun angle and practical light.',
    basePosition: [0, 0, 0],
    baseRotation: [0, 0, 0],
    explodedOffset: [0, -0.42, 0],
    layerOffset: [0, 0, 0],
    stagger: 0,
    labelHeight: 0.28,
    markerRadius: 1.6,
    focusPosition: [4.6, 2.6, 4.8],
    focusTarget: [0.1, 0.05, 0.1],
  },
  {
    id: 'back-wall',
    label: 'Aperture Wall',
    category: 'architecture',
    semanticRole: 'light catcher',
    selectable: true,
    materialCategory: 'paint',
    defaultMaterialId: 'paint-chalk',
    description: 'The rear plane is cut by a wide horizontal aperture — the room’s primary light instrument.',
    basePosition: [0, 0, -2.5],
    baseRotation: [0, 0, 0],
    explodedOffset: [0, 0.18, -1.42],
    layerOffset: [0, 0.08, 0],
    stagger: 0.08,
    labelHeight: 2.85,
    markerRadius: 1.4,
    focusPosition: [1.8, 1.9, 3.4],
    focusTarget: [0.4, 1.4, -2.5],
  },
  {
    id: 'left-wall',
    label: 'Oculus Wall',
    category: 'architecture',
    semanticRole: 'side bound',
    selectable: true,
    materialCategory: 'paint',
    defaultMaterialId: 'paint-chalk',
    description: 'A quieter plane, punctured by a circular oculus that borrows sky without opening the room.',
    basePosition: [-3.2, 0, 0],
    baseRotation: [0, 0, 0],
    explodedOffset: [-1.38, 0.16, 0],
    layerOffset: [0, 0.08, 0],
    stagger: 0.1,
    labelHeight: 2.85,
    markerRadius: 1.2,
    focusPosition: [2.6, 1.8, 2.2],
    focusTarget: [-3.2, 1.4, 0.2],
  },
  {
    id: 'sofa',
    label: 'Lounge Sofa',
    category: 'furniture',
    semanticRole: 'seating',
    selectable: true,
    materialCategory: 'fabric',
    defaultMaterialId: 'fabric-linen',
    description: 'A two-seat gallery sofa. Cushions take fabric changes immediately; the brass feet stay as structure.',
    basePosition: [1.28, 0, 0.98],
    baseRotation: [0, 0.1, 0],
    explodedOffset: [0.62, 0.58, 0.86],
    layerOffset: [0, 0.44, 0],
    stagger: 0.22,
    labelHeight: 1.05,
    markerRadius: 1.05,
    focusPosition: [3.35, 1.55, 3.15],
    focusTarget: [1.28, 0.48, 0.9],
  },
  {
    id: 'coffee-table',
    label: 'Low Table',
    category: 'furniture',
    semanticRole: 'lounge table',
    selectable: true,
    materialCategory: 'stone',
    defaultMaterialId: 'stone-travertine',
    description: 'A low slab table. Its top is the material host — stone or wood rewrites the lounge register.',
    basePosition: [1.2, 0, 0.08],
    baseRotation: [0, 0.04, 0],
    explodedOffset: [0.55, 0.86, 0.18],
    layerOffset: [0, 0.5, 0],
    stagger: 0.28,
    labelHeight: 0.55,
    markerRadius: 0.7,
    focusPosition: [2.9, 1.35, 2.5],
    focusTarget: [1.2, 0.28, 0.08],
  },
  {
    id: 'desk',
    label: 'Work Desk',
    category: 'furniture',
    semanticRole: 'work surface',
    selectable: true,
    materialCategory: 'wood',
    defaultMaterialId: 'wood-walnut',
    description: 'A cantilevered work plane on a graphite frame, parked in the raking light of the aperture.',
    basePosition: [-1.5, 0, -1.5],
    baseRotation: [0, 0, 0],
    explodedOffset: [-0.48, 0.72, -0.58],
    layerOffset: [0, 0.48, 0],
    stagger: 0.26,
    labelHeight: 0.95,
    markerRadius: 0.85,
    focusPosition: [0.55, 1.55, 1.15],
    focusTarget: [-1.5, 0.7, -1.5],
  },
  {
    id: 'chair',
    label: 'Work Chair',
    category: 'furniture',
    semanticRole: 'task seating',
    selectable: true,
    materialCategory: 'wood',
    defaultMaterialId: 'wood-ash',
    description: 'A sculptural work chair. Changing its timber shifts the temperature of the entire work zone.',
    basePosition: [-1.36, 0, -0.84],
    baseRotation: [0, 0.18, 0],
    explodedOffset: [-0.32, 0.98, -0.12],
    layerOffset: [0, 0.56, 0],
    stagger: 0.32,
    labelHeight: 1.05,
    markerRadius: 0.48,
    focusPosition: [0.4, 1.4, 1.55],
    focusTarget: [-1.36, 0.5, -0.84],
  },
  {
    id: 'daybed',
    label: 'Rest Daybed',
    category: 'furniture',
    semanticRole: 'reclining',
    selectable: true,
    materialCategory: 'fabric',
    defaultMaterialId: 'fabric-moss',
    description: 'A low daybed along the oculus wall — the rest zone, tuned by fabric rather than silhouette.',
    basePosition: [-2.42, 0, 1.22],
    baseRotation: [0, Math.PI / 2, 0],
    explodedOffset: [-0.62, 0.5, 0.78],
    layerOffset: [0, 0.42, 0],
    stagger: 0.24,
    labelHeight: 0.72,
    markerRadius: 0.95,
    focusPosition: [1.1, 1.5, 3.4],
    focusTarget: [-2.42, 0.4, 1.22],
  },
  {
    id: 'shelf',
    label: 'Rod Shelf',
    category: 'furniture',
    semanticRole: 'storage',
    selectable: true,
    materialCategory: 'wood',
    defaultMaterialId: 'wood-walnut',
    description: 'Two timber plates on brass rods. A quiet architectural note rather than a cabinet.',
    basePosition: [2.22, 0, -2.38],
    baseRotation: [0, 0, 0],
    explodedOffset: [0.42, 1.12, -0.92],
    layerOffset: [0, 0.62, 0],
    stagger: 0.34,
    labelHeight: 1.85,
    markerRadius: 0.7,
    focusPosition: [3.6, 1.7, 0.2],
    focusTarget: [2.22, 1.35, -2.2],
  },
  {
    id: 'rug',
    label: 'Lounge Rug',
    category: 'decor',
    semanticRole: 'soft ground',
    selectable: true,
    materialCategory: 'fabric',
    defaultMaterialId: 'fabric-barley',
    description: 'A squircle of fabric that anchors the lounge and drinks the color of the current mood.',
    basePosition: [1.18, 0, 0.48],
    baseRotation: [0, 0.06, 0],
    explodedOffset: [0.28, 0.28, 0.32],
    layerOffset: [0, 0.78, 0],
    stagger: 0.18,
    labelHeight: 0.22,
    markerRadius: 1.15,
    focusPosition: [3.4, 1.7, 3.3],
    focusTarget: [1.18, 0.05, 0.48],
  },
  {
    id: 'floor-lamp',
    label: 'Stem Lamp',
    category: 'lighting',
    semanticRole: 'practical light',
    selectable: true,
    materialCategory: 'metal',
    defaultMaterialId: 'metal-brass',
    description: 'A slender stem lamp. Metal finishes change the stem and base; the shade remains a paper drum.',
    basePosition: [2.52, 0, 0.7],
    baseRotation: [0, 0, 0],
    explodedOffset: [0.78, 1.32, 0.55],
    layerOffset: [0, 1.05, 0],
    stagger: 0.4,
    labelHeight: 1.85,
    markerRadius: 0.32,
    focusPosition: [4.1, 1.7, 2.5],
    focusTarget: [2.52, 1.1, 0.7],
  },
  {
    id: 'planter',
    label: 'Corner Planter',
    category: 'nature',
    semanticRole: 'vegetation',
    selectable: true,
    materialCategory: 'stone',
    defaultMaterialId: 'stone-basalt',
    description: 'A stone vessel in the aperture corner. Foliage stays living green; the pot takes stone changes.',
    basePosition: [-2.78, 0, -2.08],
    baseRotation: [0, 0.2, 0],
    explodedOffset: [-0.92, 0.48, -0.72],
    layerOffset: [0.18, 0.7, 0],
    stagger: 0.3,
    labelHeight: 1.55,
    markerRadius: 0.38,
    focusPosition: [-0.2, 1.6, 0.4],
    focusTarget: [-2.78, 0.7, -2.08],
  },
  {
    id: 'wall-art',
    label: 'Relief Panel',
    category: 'decor',
    semanticRole: 'wall composition',
    selectable: true,
    materialCategory: 'metal',
    defaultMaterialId: 'metal-brass',
    description: 'A three-mass relief. The frame and rods take metal; the inner fields stay as a fixed composition.',
    basePosition: [-3.12, 1.48, -0.42],
    baseRotation: [0, Math.PI / 2, 0],
    explodedOffset: [-1.12, 0.82, 0.22],
    layerOffset: [0, 0.86, 0],
    stagger: 0.36,
    labelHeight: 0.55,
    markerRadius: 0.42,
    focusPosition: [-0.4, 1.65, 1.5],
    focusTarget: [-3.12, 1.48, -0.42],
  },
]
